apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cal-app
  template:
    metadata:
      labels:
        app: cal-app
    spec:
      containers:
      - name: cal-container
        image: nginx:latest
        ports:
        - containerPort: 80

