apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bluegreen-app
      version: blue
  template:
    metadata:
      labels:
        app: bluegreen-app
        version: blue
    spec:
      containers:
      - name: bluegreen-container
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080


